[package]
name = "color-spantrace"
version = "0.1.2"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A pretty printer for tracing_error::SpanTrace based on color-backtrace"
repository = "https://github.com/yaahc/color-spantrace"
documentation = "https://docs.rs/color-spantrace"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-error = "0.1.2"
tracing-core = "0.1.10"
ansi_term = "0.11"

[dev-dependencies]
tracing-subscriber = "0.2.5"
tracing = "0.1.13"
